<a href="https://colab.research.google.com/github/GabeAT7/FormulaSlugOnboardingProjects/blob/main/AUTONOMOUS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(0)

N = 20000

a = torch.rand(N)*20 - 10
b = torch.rand(N)*20 - 10
x = torch.stack([a,b], 1).float()
y = (a+b).unsqueeze(1).float()

model = nn.Linear(2,1)


loss_fn = nn.MSELoss()

opt = optim.SGD(model.parameters(), lr = 1e-2)

for epoch in range(50):
  predict = model(x)
  loss = loss_fn(predict, y)
  opt.zero_grad(); loss.backward(); opt.step()
  if (epoch+1) % 10 == 0:
    print(f"epoch {epoch+1:2d} | loss {loss.item():.6f}")


model.eval()
with torch.no_grad():
  test = torch.tensor([[6.7,6.7],[4.0,6.0],[10.0,12.2]],dtype=torch.float32)
  guess = model(test).squeeze()
  print("inputs:\n",test)
  print("Predictions:\n", guess)
  print("true sums:\n", test[:,0] + test[:,1])

epoch 10 | loss 0.002035
epoch 20 | loss 0.001358
epoch 30 | loss 0.000907
epoch 40 | loss 0.000606
epoch 50 | loss 0.000404
inputs:
 tensor([[ 6.7000,  6.7000],
        [ 4.0000,  6.0000],
        [10.0000, 12.2000]])
Predictions:
 tensor([13.4194, 10.0195, 22.2192])
true sums:
 tensor([13.4000, 10.0000, 22.2000])
